In [3]:
#Import numpy
import numpy as np
import pandas as pd

In [8]:
#Exercise 1 | manual
data = [8, 12, 16, 24, 4]

mean = sum(data) / len(data)

deviations = [x - mean for x in data]
squared_deviations = [d ** 2 for d in deviations]
sum_squared_deviations = sum(squared_deviations)
variance = sum_squared_deviations / len(data)

std = variance ** 0.5
print("Standard deviation:", std)

[-4.800000000000001, -0.8000000000000007, 3.1999999999999993, 11.2, -8.8]
Standard deviation: 6.881860213634101


In [97]:
#Exercise 1 | automatic
data = [8, 12, 16, 24, 4]

std = np.std(data)

print("Standard deviation:", std)

Standard deviation: 6.881860213634101


In [17]:
#Exercise 2 | Outlier added
data = [8, 12, 16, 24, 4, 40]

std = np.std(data)

print("Standard deviation:", std)

Standard deviation: 11.925695879998877


In [98]:
#Exercise 3 |
#A) Mean is greater than 30 = true
#B) Mean is less than 30 = false
#C) Mode is greater than 30 = false
#D) Mode is less than 30 = true
#E) Both A and D = True
#F) Both B and C = False

median = 30
mean = median+1
mode = median-1
print(f"A = {mean>30}")
print(f"B = {mean<30}")
print(f"C = {mode>30}")
print(f"D = {mode<30}")
print(f"E = {mean>30 and mode<30}")
print(f"F = {mean>30 and mode>30}")





A = True
B = False
C = False
D = True
E = True
F = False


In [101]:
#Exercise 4 | Finding the median with Numpy

data = [10, 10, 10, 10, 11, 11, 12, 13, 14, 15, 15, 15, 16, 16, 16, 16, 16, 17, 18, 19, 19, 20, 20, 20, 21, 21, 21, 21, 21, 22, 22, 22, 23, 23, 
23, 24, 24, 24, 26, 26, 26, 26, 26, 26, 26, 27, 27, 27, 27, 29, 29, 29, 29, 29, 29, 29, 29, 29, 30, 30, 30, 30, 30, 31, 31, 32, 32, 33, 33, 34, 34,
35, 35, 35, 37, 37, 37, 37, 39, 39, 39, 40, 40, 43, 43, 44, 44, 46, 46, 46, 47, 49, 52, 53, 54]

median = int(np.median(data))

print("The median is:", median)

The median is: 27


In [102]:
#Exercise 5-6-7
#Positive Skew
#median
#35

my_list = []

for i in range(5):
    my_list.append(11)
for i in range(10):
    my_list.append(24)
for i in range(15):
    my_list.append(29)
for i in range(20):
    my_list.append(9)
for i in range(30):
    my_list.append(5)
for i in range(35):
    my_list.append(4)
for i in range(40):
    my_list.append(26)
for i in range(45):
    my_list.append(3)
for i in range(50):
    my_list.append(3)
for i in range(55):
    my_list.append(3)
for i in range(60):
    my_list.append(2)
for i in range(65):
    my_list.append(1)
for i in range(70):
    my_list.append(1)
for i in range(75):
    my_list.append(1)
for i in range(80):
    my_list.append(1)
for i in range(85):
    my_list.append(2)

print(my_list)    

np.median(my_list)
print('\n', "The median salary is:", median)


 The median salary is: 27


In [105]:
#Exercise 8 | Altering Mean, Median, & Mode
data_list = [1,2,3,4,5,6,7,8,9,9]
array = np.array(data_list)

median = np.median(array)
mean = np.mean(array)

def mode_finder():
    counts = np.bincount(data_list)
    mode = np.argmax(counts)
    return mode

print(median)
print(mean)
print(mode)


5.5
5.4
29


In [113]:
#Exercice 9 | Calculate the Standard Deviation  
salaries = []

for i in range(3):
    salaries.append(25)
for i in range(2):
    salaries.append(40)
for i in range(1):
    salaries.append(35)
for i in range(4):
    salaries.append(50)

print(salaries)

x = np.mean(salaries)
print(x)

print(np.std(salaries))
print(round(np.std(salaries), 1))

[25, 25, 25, 40, 40, 35, 50, 50, 50, 50]
39.0
10.44030650891055
10.4


In [116]:
#Exercise 11 
print('The Answer is C.')



The Answer is C.


In [117]:
#### 2. Print the numpy version and the configuration (★☆☆)
np.__version__, 
np.show_config

<function numpy.__config__.show()>

In [153]:
#### 3. Create a null vector of size 10 (★☆☆)
array = np.zeros(10)
print(array)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [125]:
#### 4. How to find the memory size of any array (★☆☆)
print("The size of the array is:", array.size)

The size of the array is: 10


In [152]:
a = np.empty([2,2,3], dtype= int)
print(a)

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
a.size

[[[ 1908874352  1079363356   477218585]
  [ 1077703111   477218574  1073508807]]

 [[-1908874352  1078343907 -1908874355]
  [ 1080441059  -477218588  1082134072]]]


12

In [170]:
#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)
np.arange(10,100)
array[20:-1]


array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48])

In [176]:
#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
data = [[1, 2, 3], [4, 5, 6], [7, 8, 0]]
df = np.array(data)

print(df)

[[1 2 3]
 [4 5 6]
 [7 8 0]]


In [5]:
data = [[1, 2, 3], [4, 5, 6], [7, 8, 0]]
df = pd.DataFrame(data)
df.columns = ['a','b','c']

print(df)

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  0


In [194]:
data = [[1, 2, 3], [4, 5, 6], [7, 8, 0]]
df = np.eye(2)

print(df)

[[1. 0.]
 [0. 1.]]
